### ISSUE TITLE
Link from child-documents to main-document

### ISSUE THREAD

**Issue by pat-s** [humburg/reportmd#23]
When referring from one child-document to the main-document, knitting is running infinite. 

```r
output:
  reportMD::multi_document:
    toc: true
    fig_caption: true
    highlight: dracula
    depends:
      part99: main.Rmd
```

Linking between child-documents works as expected. 

Does it always need to be like `partX: some.Rmd`? Referring to the `partX:` term.

**Comment by humburg** [comment]
The documents listed under *depends* are dependencies, i.e., it is assumed that they have to be compiled before the current one. This then allows R objects created in those documents to be loaded in the current one. Circular dependencies are not allowed, so referring to the main document in any of the children isn't possible. 

It probably would make sense to have another list, similar to *depends*, that defines labels to facilitate linking between documents without implying a direct dependency.

The label assigned to a dependency can be any syntactic R name (is that what you were asking?).

**Comment by pat-s** [comment]
Ok, thanks for clarification. 

A list showing links between all parts of the document without implying a dependency would certainly be important. To not have redundant linkage information, this could be somehow merged with the dependency information and then shown together in the 'Related documents'  tab. 

Example:

```r
output:
  reportMD::multi_document:
    toc: true
    fig_caption: true
    highlight: dracula
    depends:
      part1: part1.Rmd
      part2: part2.Rmd
    links:
      part3: main.Rmd # main document
      part4: main.Rmd # some other document without dependency
```

**Comment by humburg** [comment]
Yes, that is what I was thinking as well. I'll put it on the todo list.
