### ISSUE TITLE
Unable to locate output for chunks

### ISSUE THREAD

**Issue by pat-s** [humburg/reportmd#25]
I have three files:

- main.Rmd
- part1.Rmd
- part2.Rmd

`part2.Rmd` depends on the output of `part1.Rmd`. One code chunk of `part2.Rmd` has the following setup:

```r
{r vegindex, dependson='part1:createhyperspec'}
```

While this logic works with your example template, it does not for my code. I´m loading a raster file from disk and modify it in `part1.Rmd`. Kniting only `part1.Rmd` works. `main.Rmd` and `part2.Rmd` are failing. No code chunk caching. 

YAML header of `part2.Rmd`:

```yaml 
output:
  reportMD::multi_document:
    toc: true
    fig_caption: true
    highlight: atom-one-dark
    depends:
      part1: part1.Rmd
    use_namespace: true
```

```
Error in load_dependencies(dep) : 
  Unable to locate output for chunks createhyperspec ,  from document /Users/pjs/Servers/GIServer/home/patrick/PhD/R/presentations/hsdar/part1.Rmd.
Calls: <Anonymous> ... call_block -> as.strict_list -> hook -> load_dependencies
```

**Comment by humburg** [comment]
Without a reproducible example, it is difficult to see what is going on here. Presumably `part1.Rmd` actually contains a chunk called *createhyperspec* (i.e. this isn't due to a typo) and that chunk is cached? Does rendering `part1.Rmd` create files `/Users/pjs/Servers/GIServer/home/patrick/PhD/R/presentations/hsdar/part1_cache/html/createhyperspec_*`?

**Comment by pat-s** [comment]
`part1/html/createhyperspec*` are created. I zipped everything so you can hopefully reproduce the error. 

Thanks for your valuable time here! 

[Archive.zip](https://github.com/humburg/reportmd/files/782684/Archive.zip)

**Comment by humburg** [comment]
Since you are using `use_namespace=TRUE` you should access `hyperspecs` as `part1$hyperspecs`.

**Comment by pat-s** [comment]
@humburg thanks, works now! So much time for this little problem :no_mouth:

I thought that I tried it once with `use_namespace:false` but apparently I did not..
