### ISSUE TITLE
Referring to ext_cars in the part2 of base template

### ISSUE THREAD

**Issue by pasichnyi** [humburg/reportmd#35]
When creating a brand new multi-report using the template, knit fails for the main rmarkdown (`Test.Rmd`):
> Quitting from lines 193-194 (Test.Rmd) 
> Error in rownames(ext_cars) : object 'ext_cars' not found
> Calls: <Anonymous> ... f -> scales_add_defaults -> lapply -> FUN -> rownames

Meaning, it cannot use the `ext_cars` dataframe that is defined in `part1.Rmd` later in `part2.Rmd`.
At the same time, I can knit `part1.Rmd` and `part2.Rmd` without any problems.

Any ideas on what could be wrong here?

**Comment by humburg** [comment]
I see what you mean.  It looks like the problem is that when the graph created in part 2 is plotted in the main document it can't access the R objects created in part 1.

I'll see whether I can come up with a more robust way of handling this case. You should be able to work around the problem by ~setting the parent of the part2 environment to the part1 environment~ adding `attach(part2)` before the call to plotMD() in the main document.

**Comment by pasichnyi** [comment]
Thanks a lot, that worked out well.

Do I understand correctly that it the best practice for the cases for a few-times use of objects from the child docs (that is intended in `use_namespace: true` case)?

What is your recommendation for the cases when that objects created in the child doc (or even R script) should be available globally throughout the main document (e.g. main dataframe or some heavily-used custom functions)

**Comment by humburg** [comment]
If you use `use_namespace: false` you don't need the above workaround. But that will pull all objects from the included child documents end up in the global environment of the current document. That isn't usually desirable. If you have several child documents that you'd like to use the namespacing with but one or two that should go into the global namespace (data import and functions, say) you could use `use_namespace: true` and then `attatch()` the environments you want globally in the setup chunk.

**Comment by pasichnyi** [comment]
Thank you for the prompt reaction and detailed explanations, that helped a lot!
