### ISSUE TITLE
Problem displaying multipart report in RStudio

### ISSUE THREAD

**Issue by katieburnham** [humburg/reportmd#8]
When using the multipart report template in RStudio (Version 0.99.903), all individual documents are compiled correctly but RStudio crashes when trying to display the html file generated. There is no problem when rmarkdown::render() is called on the main document directly.

**Comment by humburg** [comment]
Thanks for reporting this. It looks to me as if this is an issue with RStudio. I've reported it [there](https://support.rstudio.com/hc/en-us/community/posts/214037928-Using-knit-button-crashes-RStudio?page=1#community_comment_219034888).

**Comment by kevinushey** [comment]
IDE member following up here -- can you provide a simple reproducible example? FWIW package installation currently fails for me:

```
> devtools::install_github("humburg/reportmd")
Downloading GitHub repo humburg/reportmd@master
from URL https://api.github.com/repos/humburg/reportmd/zipball/master
Installing reportMD
'/Library/Frameworks/R.framework/Resources/bin/R' CMD INSTALL '/private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/RtmpoUJz0r/devtools981849442821/humburg-reportmd-649dea7' 
Error: Command failed:
 '/Library/Frameworks/R.framework/Resources/bin/R' CMD INSTALL '/private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/RtmpoUJz0r/devtools981849442821/humburg-reportmd-649dea7'  
 * installing to library ‘/Users/kevin/Library/R/3.3/library’
* installing *source* package ‘reportMD’ ...
** R
** inst
** preparing package for lazy loading
Error : object ‘clean_source’ is not exported by 'namespace:devtools'
ERROR: lazy loading failed for package ‘reportMD’
* removing ‘/Users/kevin/Library/R/3.3/library/reportMD’
```

For reference, I have the current development version of `devtools` installed, so perhaps that function is no longer provided for some reason?

**Comment by humburg** [comment]
@kevinushey It looks like `clean_source` was removed from `devtools` in November. I've removed that dependency so hopefully you should be able to install the package now.

The easiest way I have to reproduce this issue is to 
1. install reportMD 
2. in RStudio go to File > New File > R Markdown > From Template > Multi-part Report
3. Open the main document (the name will be the one you chose in step 2)
4. Press the *knit* button

This should then compile all the files in the template and crash when trying to open the resulting web page.

**Comment by humburg** [comment]
I'm in the process of reworking parts of the package and in the process managed to improve the situation slightly. Using the latest development version (#10) the generated web page is now displayed correctly. However, clicking on a tab in the appendix will still crash RStudio. It works fine in Chrome and Firefox.

**Comment by humburg** [comment]
As best as I can tell the latest release of reportMD doesn't suffer from this issue anymore. @katieburnham let me know if you continue to have problems.
